Add support for LTI 1.3 related directives
apluslms/a-plus-rst-tools pull request #161
Opened 2023-05-31 09:02 UTC by PasiSa

# Description

**What?**

Relates to https://github.com/apluslms/a-plus/pull/1175 and https://github.com/apluslms/gitmanager/pull/34 , and should be merged about at the same time.

**Why?**

[ANSWER HERE]

**How?**

[ANSWER HERE]

Fixes #<issue number>

# Testing

**Remember to add or update unit tests for new features and changes.**

* How to [test your changes in A-plus](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations)
* How to [test accessibility](https://wiki.aalto.fi/display/EDIT/How+to+check+the+accessibility+of+pull+requests)

**What type of test did you run?**

- [ ] Accessibility test using the [WAVE](https://wave.webaim.org/extension/) extension.
- [ ] Django unit tests.
- [ ] Selenium tests.
- [ ] Other test. *(Add a description below)*
- [ ] Manual testing.

[ADD A DESCRIPTION ABOUT WHAT YOU TESTED MANUALLY]

**Did you test the changes in**

- [ ] Chrome
- [ ] Firefox
- [ ] This pull request cannot be tested in the browser.

**Think of what is affected by these changes and could become broken**

# Translation

- [ ] Did you modify or add new strings in the user interface? ([Read about how to create translation](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations))

# Programming style

- [ ] Did you follow our [style guides](https://apluslms.github.io/contribute/styleguides/)?
- [ ] Did you use Python type hinting in all functions that you added or edited? ([type hints](https://docs.python.org/3/library/typing.html) for function parameters and return values)

# Have you updated the README or other relevant documentation?

- [ ] documents inside the doc directory.
- [ ] README.md.
- [ ] Aplus Manual.
- [ ] Other documentation (mention below which documentation).

# Is it Done?

- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

*Clean up your git commit history before submitting the pull request!*

2023-06-08 17:44 UTC, Mankro commented
Does this pull request fix #160?

2023-06-08 17:49 UTC, Mankro approved these changes
This looks good, though you could validate incorrect user input better, e.g., mixing options from different LTI versions.

2023-06-08 17:49 UTC, Mankro commented on directives/submit.py
> +            if 'lti1p3' in self.options:
You could raise a `SphinxError` if both `lti` and `lti1p3` options are set.

2023-06-13 15:21 UTC, Mankro commented
It would also be good to update the README and add a short description of the new options.

2023-06-16 15:04 UTC, Mankro requested changes
Would you still fix the typos and add the "Fixes #160" text to the git commit message?

2023-06-16 15:04 UTC, Mankro commented on directives/submit.py
> +                if 'lti1p3' in self.options:
Should we also check that `lti_custom` is not used with `lti` and `lti_aplus_get_and_post` is not used with `lti1p3`? What about `lti_context_id` and `lti_resource_link_id`?

2023-06-17 08:37 UTC, PasiSa commented
Sorry for my sloppyness, fixed now.

2023-06-18 21:22 UTC, Mankro approved these changes

2023-06-18 21:24 UTC, merged